apiVersion: apps/v1
kind: Deployment
metadata:
  name: karting-frontend-deployment
  labels:
    app: karting-frontend-deployment
spec:
  selector:
    matchLabels:
      app: karting-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: karting-frontend-deployment
    spec:
      containers:
        - name: karting-frontend-container
          image: calpz/karting-frontend-image
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: karting-frontend-service
  labels:
    app: karting-frontend
spec:
  selector:
    app: karting-frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer