apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-discounts1-deployment
  labels:
    app: ms-discounts1-deployment
spec:
  selector:
    matchLabels:
      app: ms-discounts1-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-discounts1-deployment
    spec:
      containers:
        - name: ms-discounts1
          image: calpz/ms-discounts1-image
          ports:
            - containerPort: 8002
          env:
            - name: SERVER_PORT
              value: "0"