pipeline {
    agent any
    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Linna-Lpz/Tingeso-1-KartingRM']])
                dir("kartingFrontend") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("kartingFrontend") {
                    script {
                        bat "docker context use default"
                        withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat "docker build -t calpz/karting-frontend-image ."
                            bat "docker push calpz/karting-frontend-image"
                        }
                    }
                }
            }
        }
    }
}